name: django
channels:
  - conda-forge
  - defaults
dependencies:
  - python<=3.6.13
  - django<=3.17
  - djangorestframework<=3.12.2
  - pip
  - pillow<=8.1.2
  # caso queira fazer deploy no heroku
  # pip:
  # - django-heroku<=0.3.1