# Generated by Django 3.1.7 on 2021-03-18 03:21

from django.db import migrations, models
import livros.models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=livros.models.upload_imagem_livro),
        ),
    ]
